### ISSUE TITLE
几种常见的水平垂直居中

### ISSUE THREAD

**Issue by nikoohp** [nikoohp/Front-end-development#2]
## 第一种：
```scss
.parent{
   position: relative;

  .child{
     $width:100px;
     $height:100px;
     position: absolut;
     left:50%;
     top:50%;
     margin-left: - $width / 2;
     margin-top: - $height / 2;
  }
}
```

## 第二种（利用css3）
```scss
.parent{
   position: relative;

  .child{
     $width:100px;
     $height:100px;
     position: absolut;
     left:50%;
     top:50%;
     transform: translate3d(-50%, -50%, 0);
  }
}
```

## 第三种
```scss
.parent{
   position: relative;

  .child{
     position: absolut;
     left:0;
     top:0;
     top: 0;
     bottom: 0;
     margin: auto;
  }
}
```
